config/routes.rb
Rails.application.routes.draw do

  resources :users
  get 'home/index'
  root 'home#index'

  resources :properties do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :users

  #get 'sessions/new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: {minimum: 15}
  validates :price, presence: true, length: {minimum: 2}
  validates :address, presence: true, length: {minimum: 10}
  validates :image, file_size: {less_than: 5.megabytes}

  mount_uploaders :images, ImageUploader
  serialize :images, JSON

end

app/models/user.rb
class User < ApplicationRecord

has_secure_password

validates :email, presence: true, uniqueness: true

validates :name, presence: true

validates :surname, presence: true

validates :address, presence: true

validates :phone, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @property = Property.find(params[:property_id])
    @comment = @property.comments.create(comment_params)
    redirect_to property_path(@property)
  end

  def destroy
    @property = Property.find(params[:property_id])
    @comment = @property.comments.find(params[:id])
    @comment.destroy
    redirect_to property_path(@property)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = Property.all
  end

  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
  end

  def edit
    @property = Property.find(params[:id])
  end

  def create
    @property = Property.new(property_params)

    if @property.save
      redirect_to properties_path
    else
      render 'new'
    end
  end

  def update
    @property = Property.find(params[:id])

    if @property.update(property_params)
      redirect_to @property
    else
      render 'edit'
    end

  end

  def destroy
  @property = Property.find(params[:id])
  @property.destroy

  redirect_to properties_path
end

  private
  def property_params
    params.require(:property).permit(:title, :address, :price, :description, :image, {images: []})
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  user = User.find_by_email (params[:email])
  if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to root_url
  else
    flash.now[:alert] = 'Email or password is invalid'
    render "new"
  end
end

  def destroy
  session[:user_id] = nil
  redirect_to root_url, notice: 'Logged out!'
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
      @user = User.new
    end

    def create
      @user = User.new(allowed_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_url, notice: 'Thank you for signing up!'
      else
        render :new
      end
    end

    private

    def allowed_params
      params.require(:user).permit(:name, :surname, :address, :phone, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.property, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @property, @property.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to Chambers!</h1>


<% if current_user %>
Logged in as <%= current_user.name %><br/><br/>
  <%= link_to 'Log out', logout_path %><br/><br/>
  <%= link_to 'Properties', controller: 'properties' %>
<% else %>
  <%= link_to 'Sign up', signup_path %>
  <%= link_to 'Log in', login_path %>
<% end %>

<p id=”notice”><%= notice %></p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <ul class="nav nav-pills">
        <li role="presentation" class="active"><a href="#">Home<span class="badge"></span></a></li>
        <li role="presentation"><a href="#">Profile</a></li>
        <li role="presentation"><a href="#">Messages</a></li>


<%#museful to highlight unread messages
<button class="btn btn-primary" type="button">
  Messages <span class="badge">4</span>
</button>
%>
  <li role="presentation"><a href="#">Properties</a></li>
  <li role="presentation"><a href="#">Help</a></li>
</ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chambers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |name, msg| %>
     <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

    <%= render 'layouts/navigation' %>
    <%= yield %>

    <% unless flash.empty? %>
         <script type="text/javascript">
              <% flash.each do |f| %>
    	      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
    	     	 toastr['<%= type %>']('<%= f[1] %>');
    	   <% end %>
         </script>
    <% end %>

  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with model: @property, local: true do |form| %>

  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@property.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @property.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </p>

  <p>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :images %><br>
    <%= form.file_field :images, multiple: true %>
    <%= form.hidden_field :image_cache %>
  </p>

  <p>
    <%= form.submit %>
  </p>

 <%= render 'shared/errors', object: @property %>

<% end %>

app/views/properties/_property.html.erb
<h2><%= link_to property.title, property_path(property) %></h2>

<p><%= truncate(post.body, length: 150) %></p>

<p><%= link_to 'Edit', edit_property_path(property) %></p>
<hr>

app/views/properties/edit.html.erb
<h1>Edit Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<h1>Available properties</h1>

<%= link_to 'New Property', new_property_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Address</th>
    <th>Price</th>
    <th>Description</th>

    <th colspan="5"></th>
  </tr>

  <% @properties.each do |property| %>
    <tr>
      <td><%= property.title %></td>
      <td><%= property.address %></td>
      <td><%= property.price %></td>
      <td><%= property.description %></td>


      <td><%= link_to 'Show', property_path(property) %></td>
      <td><%= link_to 'Edit', edit_property_path(property) %></td>
      <td><%= link_to 'Destroy', property_path(property),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Log out', logout_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>
<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @property.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @property.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<p>
  <strong>Images:</strong>

</p>

<% if @property.images? %>
  <ul>
    <% @property.images.each do |image| %>
      <li><%= link_to(image_tag(image.big_thumb.url, alt: 'Image'), image.url, target: '_blank') %></li>
    <% end %>
  </ul>
<% end %>

<h2>Comments</h2>
<%= render @property.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <h3>The following errors were found:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>

      <h2>Please correct the errors</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>

  <% end %>

  <%= form_for @user do |f| %>

    <%= f.label :name %><br />
    <%= f.text_field :name %><br />

    <%= f.label :surname %><br />
    <%= f.text_field :surname %><br />

    <%= f.label :address %><br />
    <%= f.text_field :address %><br />

    <%= f.label :phone %><br />
    <%= f.text_field :phone %><br />

    <%= f.label :email %><br />
    <%= f.email_field :email %><br />

    <%= f.label :password %><br />
    <%= f.password_field :password %><br />

    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %><br /><br />

  <%= f.submit "Sign Up" %>

  <% end %>

  <p><strong>Already have an account?</strong></p>
  <%= link_to 'Log in', login_path %><br /><br />

<% end %>